title: Darling September
email: hello@darlingseptember.com
description: > #
  Dragica is a Belgrade-born, Amsterdam-based digital creative, with a passion for photography and storytelling.
baseurl: ""
url: "https://darlingseptember.com"
markdown: kramdown
theme: minima
